project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sanjeet"

  page-footer:
    left: "&copy; Copyright 2022, Author"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects/index.qmd
        text: Projects

      - href: about.qmd
        text: About
    
      - href: CV.qmd
        text: CV
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



